Add parsing option to CLI

diff --git a/debdroid/data/data/com.termux/files/usr/bin/debdroid b/debdroid/data/data/com.termux/files/usr/bin/debdroid
--- a/debdroid/data/data/com.termux/files/usr/bin/debdroid
+++ b/debdroid/data/data/com.termux/files/usr/bin/debdroid
@@ -1,5 +1,5 @@
 #!/data/data/com.termux/files/usr/bin/bash
-### DEBDROID v2.16-R3.
+### DEBDROID v2.17.
 ### Made By WMCB Tech @wmcbtech30
 ### This script should not be modified at some cases
 ### Dependencies Required
@@ -56,6 +56,12 @@ show_help(){
 	echo " --no-shared	Launches Debian Distribution without host storage access"
 	echo " --import	Imports the Debian Container Image"
 	echo " --export	Exports the Debian Container Image"
+	echo ""
+	echo "To Pass Command within DebDroid. use the '--' option or '---' if isolated"
+	echo "e.g.:"
+	echo "	debdroid -- sudo apt update"
+	echo "	debdroid -- nano"
+	echo "	debdroid --- sudo apt upgrade"
 	exit 2
 }
 
@@ -216,6 +222,73 @@ launch-isol() {
 	/bin/su -l $(cat $ROOTFS/etc/userinfo.rc)
 }
 
+parse-cmd() {
+	if [ -e $STATUS ]; then
+    		echo ""
+	else
+    		echo "Cannot start Debian Container. Please install it using debdroid --install"
+		exit 2
+	fi
+	unset LD_PRELOAD
+	proot --link2symlink --kill-on-exit \
+	-0 -r $ROOTFS -p \
+	-b /dev \
+	-b /proc \
+	-b /sys \
+	-b /dev/urandom:/dev/random \
+	-b /proc/self/fd:/dev/fd \
+	-b /proc/self/fd/0:/dev/stdin \
+	-b /proc/self/fd/1:/dev/stdout \
+	-b /proc/self/fd/2:/dev/stderr \
+	-b $PREFIX/tmp:/dev/shm \
+	-b $PREFIX/tmp:/tmp \
+	-b $ROOTFS/proc/stat:/proc/stat \
+	-b $ROOTFS/proc/version:/proc/version \
+	-b /storage/emulated/0:/sdcard \
+	-b /data \
+	-b /system \
+	-b /:/host-rootfs \
+	/usr/bin/env -i \
+	TERM=xterm-256color \
+	HOME=/root \
+	USER=root \
+	PATH="$PATHBASE" \
+	TMPDIR=/tmp \
+	LANG=C.UTF-8 \
+	sudo -u $(cat $ROOTFS/etc/userinfo.rc) "$@"
+}
+
+parse-cmd-isol() {
+	if [ -e $STATUS ]; then
+    		echo ""
+	else
+    		echo "Cannot start Debian Container. Please install it using debdroid --install"
+		exit 2
+	fi
+	unset LD_PRELOAD
+	proot --link2symlink --kill-on-exit \
+	-0 -r $ROOTFS -p \
+	-b /dev \
+	-b /proc \
+	-b /sys \
+	-b /proc/self/fd:/dev/fd \
+	-b /proc/self/fd/0:/dev/stdin \
+	-b /proc/self/fd/1:/dev/stdout \
+	-b /proc/self/fd/2:/dev/stderr \
+	-b $PREFIX/tmp:/dev/shm \
+	-b $PREFIX/tmp:/tmp \
+	-b $ROOTFS/proc/stat:/proc/stat \
+	-b $ROOTFS/proc/version:/proc/version \
+	-w /root \
+	/usr/bin/env -i \
+	TERM=xterm-256color \
+	HOME=/root \
+	USER=root \
+	PATH="$PATHBASE" \
+	TMPDIR=/tmp \
+	LANG=C.UTF-8 \
+	sudo -u $(cat $ROOTFS/etc/userinfo.rc) "$@"
+}
 
 if [ $# = 0 ]; then
 	show_help
@@ -246,6 +319,12 @@ case "$CMD" in
 		;;
 	-h|--show-help)
 		show_help
+		;;
+	--)
+		parse-cmd "$@"
+		;;
+	---)
+		parse-cmd-isol "$@"
 		;;
 	*) echo "Unknown Command: '$CMD'"; exit 2;;
 esac
